### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by ElJaviLuki** [Deepest-Project/MelNet#27]
After doing
`!python trainer.py -c ./config/kss.yaml -n testrun -t 1 -b 30 -s testtts`
(take in account that I don't what are most of those parameters for)

I get:
```2021-08-05 10:19:11.179380: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
100% 12854/12854 [00:00<00:00, 161586.27it/s]
100% 12854/12854 [00:00<00:00, 280440.60it/s]
Train data loader:   0% 0/368 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/MelNet/utils/train.py", line 98, in train
    audio_lengths.cuda(non_blocking=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MelNet/model/tts.py", line 143, in forward
    h_t, h_f, h_c = layer(h_t, h_f, h_c, audio_lengths)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MelNet/model/rnn.py", line 75, in forward
    h_t_yz, _ = self.t_delay_RNN_yz(h_t_yz_temp)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py", line 543, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py", line 526, in forward_impl
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 1.35 GiB (GPU 0; 14.76 GiB total capacity; 12.76 GiB already allocated; 1.01 GiB free; 141.28 MiB cached)
Train data loader:   0% 0/368 [01:04<?, ?it/s]

**Comment by ElJaviLuki** [comment]
Reducing the `-b` or `--batch-size` solved the problem.
